### ISSUE TITLE
I can register with a password not following the pw-strength meter rules

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#235]
Dev-Note:
The validation rules of the register/reset-forms does not contain a password strength rule. This rule is calculated separately and controls only the error message of the password input field. Password length is checked (8 characters minimum), but "xxxxxxxx" is allowed.

To solve add a password strength validator and remove the old strength validation code.
It could be useful to also add a pw-validation service because the reset-form also uses password-validation.

**Comment by afalenski** [comment]
Yes, it is not possible to register using password "xxxxxxxx". But it is possible to use password "xxxXXXXx". Safer would be a password with small letters, capital letters, at least one digit and one special character (like -!?%). 

We need to discuss this.

**Comment by GerberI** [comment]
I move this ticket to review again. I think the bug is fixed. The submit button gets only activated if the strength meter is not red. The rules for the password strength itself should indeed be discussed. This could be done during the security overhaul after the audit and in a separate ticket.

**Comment by afalenski** [comment]
I can still click the button "Registrieren", when I register and use the password "xxxxXXXx". Bug not fixed. 
Additional oddity: I get an email with a button "Aktivieren Sie Ihr Konto" and when I push this button, I get a MiBi-Portal toaster "Kontoaktivierung fehlgeschlagen. Bitte kontaktieren Sie das MiBi-Portal-Team." with the additional message "Ihre Kontoaktivierung ist fehlgeschlagen. Bitte erneut registrieren." + Button "Weiter zur Registrierung".

Could it be that the password is only checked in the backend but not in the frontend?

**Comment by afalenski** [comment]
OK, misunderstanding. The password is now rejected when the password strength is bad (red bar). Ticket done.
Password rules will be ameliorated in a separate ticket.
